---
version: "3.7"
services:
  kasm:
    build: .
    image: kasm-python-workspace
    ports:
      - "6901:6901"
    environment:
      VNC_PW: password
    shm_size: '512m'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: bridge
    volumes:
      - type: bind
        source: ./kasm_user
        target: /home/kasm-user

# to get Chrome working per https://stackoverflow.com/a/64460373
    security_opt:
      - seccomp=./chrome.json
...