---
# Add Ansible Galaxy Packages here, role_example_hello included to prevent errors in template testing
roles:
- irixjp.role_example_hello           # https://galaxy.ansible.com/irixjp/role_example_hello
collections:
- community.postgresql                # https://galaxy.ansible.com/community/postgresql
...
