---
# Add Ansible Galaxy Packages here, role_example_hello included to prevent errors in template testing
collections:
- community.postgresql                # https://galaxy.ansible.com/community/postgresql
...
